language: cpp
dist: trusty
sudo: required

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

env:
  global:
  - DOCKER_IMAGE="umrdbs/mapping-dependencies:latest"
  - DOCKER_CONTAINER="mapping_container"
  - DOCKER_CONTAINER_HOME="/app"
  - MAPPING_CORE="umr-dbs/mapping-core"

before_install:
- docker pull $DOCKER_IMAGE
- docker run -d
  --name $DOCKER_CONTAINER 
  --volume "$(pwd)":"$DOCKER_CONTAINER_HOME/$TRAVIS_REPO_SLUG"
  $DOCKER_IMAGE
- docker exec -t
  -w "$DOCKER_CONTAINER_HOME"
  $DOCKER_CONTAINER
  git clone --depth 1 https://github.com/$MAPPING_CORE.git $MAPPING_CORE

script:
- docker exec -t 
  -w "$DOCKER_CONTAINER_HOME/$MAPPING_CORE"
  $DOCKER_CONTAINER
  cmake -DCMAKE_BUILD_TYPE=Release -DMAPPING_MODULES="mapping-gfbio" .
- docker exec -t
  -w "$DOCKER_CONTAINER_HOME/$MAPPING_CORE"
  $DOCKER_CONTAINER make
  -j$(cat /proc/cpuinfo | grep processor | wc -l)
- docker exec -t
  -w "$DOCKER_CONTAINER_HOME/$MAPPING_CORE"
  $DOCKER_CONTAINER
  make test

notifications:
  slack:
    secure: tNx4zp411stqUv0yHVafptjBz5L+6z+tHjmNOz6TyIczY/xslmK39y8/TULYNRfnzPG3OSu1r9lL0auQ6d45gOdXj21MJkXed9qTPGAcWX4nBGFOCVwO0HUuY/O7p8cumOpmhOcGCqL/BY+UsCPK9tpK6KZOIfDbJFmMxi3rrnjP2no7OEzd3vxuoAgsHSc+3DWyOcBDmJRoadAPxjEig4o34wLpCIWLeajG7kyNoXk60BgOw2JVx45wWMfG2PemhzDEh94ehMU9R8f+NBkAiP13oB0CwTei2PkiKCB8qVeLX1Fuf5ejaxR42Pmfad/EDTELkUnV885sH05mhcsdwByuhkh2p914qHchvjJnF+BDgjBmpADCRFIDxEKUfXsxnh7XPEvkkC1jm9hCdOXEx/PhF/Umm2a6G7O5DpCjf9IG2mxAKoeoych+aY7zEU/fYM651c6uZzmO7+cTtGylGkw8FIoufrROmuMqZWu+EOCr61h5Tp5wCHGViIlMLadt2Ot49G0GqBeTtaq406R9OMWU3fCz8/mkD/leWrpPdJyd4o9hHgEX+UKcTyW6Zg9ffF5rok0hphLZ/ik2br3pSm0AoVatDmvB+zbMi98MJ3O8dO2Nz3PfVYoSgucnC5OxFjqujDjbT7rVFRUeD7aU4+0oeDWYPWfxGW/fXIcgYl0=
